#!/usr/bin/env python3
"""Generates the synthetic HAR fixtures in tests/fixtures/har (SPEC 12.3).

Every value is invented; no real capture is used. Run from the repository root:

    python3 scripts/fixtures/make_fixtures.py

The 200,000-entry and 1 GB fixtures are generated by the test suite at test time
(tests/HarLens.Core.Tests/Fixtures/LargeHarGenerator.cs), not here.
"""
import base64
import gzip
import json
import os
import struct
import zlib

OUT = os.path.join("tests", "fixtures", "har")

# Brotli encoding of BROTLI_TEXT, produced with System.IO.Compression.BrotliStream
# (Python's standard library has no brotli encoder).
BROTLI_TEXT = '{"compressed":"brotli","message":"This body was stored as brotli bytes in the HAR.","items":[1,2,3]}'
BROTLI_B64 = ("G2MAYJwHtq1k70L0wV6LAzMUhtLCfzun9fe26eZbTcSglOJKkmbR6RKbLjFBJTOjkyM9EP5fYgkEWYBRLMEO2NkZfITiPp"
              "bVn1aJrxmjAyKJ0K0tnbx1U6dgoXJjU2m32w4YoHakcB8=")

# A 1x1 transparent PNG and GIF.
PNG_1X1 = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==")
GIF_1X1 = base64.b64decode("R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7")


def h(*pairs):
    return [{"name": n, "value": v} for n, v in pairs]


def iso(base_ms):
    """2026-10-07T09:00:00.000Z plus base_ms milliseconds."""
    total_ms = int(base_ms)
    s, ms = divmod(total_ms, 1000)
    m, s = divmod(s, 60)
    hh, m = divmod(m, 60)
    return "2026-10-07T%02d:%02d:%02d.%03dZ" % (9 + hh, m, s, ms)


def timings(blocked=1.2, dns=-1, connect=-1, ssl=-1, send=0.3, wait=40.0, receive=2.5):
    return {"blocked": blocked, "dns": dns, "ssl": ssl, "connect": connect,
            "send": send, "wait": wait, "receive": receive}


def total(t):
    return round(sum(v for k, v in t.items() if k != "ssl" and isinstance(v, (int, float)) and v > 0), 3)


def entry(method, url, status, mime, text=None, *, start_ms=0, req_headers=(), resp_headers=(),
          http_version="HTTP/1.1", status_text=None, encoding=None, post=None, t=None, extra=None,
          resp_extra=None, req_extra=None, size=None, body_size=None, headers_size=-1):
    t = t or timings()
    content = {"size": size if size is not None else (len(text.encode()) if text and encoding is None else 0),
               "mimeType": mime}
    if text is not None:
        content["text"] = text
    if encoding:
        content["encoding"] = encoding
    request = {
        "method": method, "url": url, "httpVersion": http_version,
        "headers": h(*req_headers), "queryString": query_of(url), "cookies": [],
        "headersSize": -1, "bodySize": len(post["text"].encode()) if post and "text" in post else 0,
    }
    if post:
        request["postData"] = post
    if req_extra:
        request.update(req_extra)
    response = {
        "status": status, "statusText": status_text if status_text is not None else STATUS_TEXT.get(status, ""),
        "httpVersion": http_version, "headers": h(*resp_headers), "cookies": [],
        "content": content, "redirectURL": "", "headersSize": headers_size,
        "bodySize": body_size if body_size is not None else content["size"],
    }
    if resp_extra:
        response.update(resp_extra)
    e = {
        "startedDateTime": iso(start_ms), "time": total(t), "request": request, "response": response,
        "cache": {}, "timings": t,
    }
    if extra:
        e.update(extra)
    return e


def query_of(url):
    if "?" not in url:
        return []
    q = url.split("?", 1)[1].split("#", 1)[0]
    out = []
    for part in q.split("&"):
        if not part:
            continue
        n, _, v = part.partition("=")
        out.append({"name": n, "value": v})
    return out


STATUS_TEXT = {0: "", 101: "Switching Protocols", 200: "OK", 204: "No Content", 301: "Moved Permanently",
               302: "Found", 304: "Not Modified", 403: "Forbidden", 404: "Not Found", 413: "Payload Too Large",
               500: "Internal Server Error", 503: "Service Unavailable"}


def log(entries, creator=("SyntheticBrowser", "1.0"), version="1.2", pages=None, browser=None, comment=None):
    lg = {"version": version, "creator": {"name": creator[0], "version": creator[1]}}
    if browser:
        lg["browser"] = {"name": browser[0], "version": browser[1]}
    if pages is not None:
        lg["pages"] = pages
    lg["entries"] = entries
    if comment:
        lg["comment"] = comment
    return {"log": lg}


def write(name, doc, indent=2, bom=False):
    path = os.path.join(OUT, name)
    text = json.dumps(doc, indent=indent, ensure_ascii=False)
    data = text.encode("utf-8")
    if bom:
        data = b"\xef\xbb\xbf" + data
    with open(path, "wb") as f:
        f.write(data)
    return data


def chromium():
    page = {"startedDateTime": iso(0), "id": "page_1", "title": "https://www.contoso-shop.test/",
            "pageTimings": {"onContentLoad": 812.4, "onLoad": 1544.9}}
    chrome_t = lambda **k: dict(timings(**k), _blocked_queueing=0.8, _workerStart=-1, _workerReady=-1,
                                _workerFetchStart=-1, _workerRespondWithSettled=-1)
    base = {"pageref": "page_1", "connection": "40121", "serverIPAddress": "203.0.113.10"}
    h2_req = lambda path, host="www.contoso-shop.test": [
        (":authority", host), (":method", "GET"), (":path", path), (":scheme", "https"),
        ("accept", "*/*"), ("accept-encoding", "gzip, deflate, br, zstd"), ("accept-language", "en-GB,en;q=0.9"),
        ("user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) SyntheticBrowser/1.0")]
    html = "<!doctype html><html><head><title>Contoso Shop</title><link rel=stylesheet href=/site.css></head><body><h1>Shop</h1><script src=/app.js></script></body></html>"
    entries = [
        entry("GET", "https://www.contoso-shop.test/", 200, "text/html", html, start_ms=0, http_version="http/2.0",
              req_headers=h2_req("/") + [("cookie", "session=abc123; theme=dark")],
              resp_headers=[("content-type", "text/html; charset=utf-8"), ("content-encoding", "br"),
                            ("x-azure-ref", "20261007T090000Z-17c8d8f9b6d"), ("x-cache", "TCP_MISS"),
                            ("set-cookie", "session=abc123; Path=/; Secure; HttpOnly; SameSite=Lax"),
                            ("date", "Wed, 07 Oct 2026 09:00:00 GMT")],
              t=chrome_t(dns=12.1, connect=48.3, ssl=30.2, wait=120.5, receive=8.1),
              extra=dict(base, _initiator={"type": "other"}, _priority="VeryHigh", _resourceType="document"),
              resp_extra={"_transferSize": 1532, "_error": None, "_fetchedViaServiceWorker": False},
              headers_size=-1, body_size=980),
        entry("GET", "https://www.contoso-shop.test/site.css", 200, "text/css", "body{font-family:sans-serif;color:#222}h1{margin:0}",
              start_ms=210, http_version="http/2.0", req_headers=h2_req("/site.css"),
              resp_headers=[("content-type", "text/css"), ("cache-control", "max-age=3600")],
              extra=dict(base, _initiator={"type": "parser", "url": "https://www.contoso-shop.test/", "lineNumber": 1},
                         _priority="VeryHigh", _resourceType="stylesheet"),
              resp_extra={"_transferSize": 412, "_error": None}),
        entry("GET", "https://www.contoso-shop.test/app.js", 200, "application/javascript",
              "fetch('/api/cart').then(r => r.json()).then(console.log);", start_ms=220, http_version="http/2.0",
              req_headers=h2_req("/app.js"), resp_headers=[("content-type", "application/javascript")],
              extra=dict(base, _initiator={"type": "parser", "url": "https://www.contoso-shop.test/", "lineNumber": 1},
                         _priority="Medium", _resourceType="script"),
              resp_extra={"_transferSize": 377, "_error": None}),
        entry("GET", "https://www.contoso-shop.test/api/cart?currency=GBP&include=items", 200, "application/json",
              '{"cart":{"id":"c-1001","items":[{"sku":"A-1","qty":2,"price":9.99},{"sku":"B-7","qty":1,"price":24.5}],"total":44.48}}',
              start_ms=480, http_version="http/2.0",
              req_headers=h2_req("/api/cart?currency=GBP&include=items") + [("x-requested-with", "XMLHttpRequest")],
              resp_headers=[("content-type", "application/json"), ("x-ms-request-id", "7a1f6c1e-0d3b-4b8e-9b55-0c2d7f4e1a10"),
                            ("x-cache", "TCP_MISS")],
              t=chrome_t(wait=310.4, receive=1.9),
              extra=dict(base, _initiator={"type": "script", "stack": {"callFrames": [
                  {"functionName": "", "scriptId": "17", "url": "https://www.contoso-shop.test/app.js",
                   "lineNumber": 0, "columnNumber": 0}]}}, _priority="High", _resourceType="fetch"),
              resp_extra={"_transferSize": 301, "_error": None}),
        entry("GET", "https://cdn.contoso-shop.test/img/pixel.png", 200, "image/png",
              base64.b64encode(PNG_1X1).decode(), encoding="base64", size=len(PNG_1X1), start_ms=500,
              http_version="http/2.0", req_headers=h2_req("/img/pixel.png", "cdn.contoso-shop.test"),
              resp_headers=[("content-type", "image/png"), ("x-cache", "TCP_HIT")],
              extra=dict(base, _initiator={"type": "parser", "url": "https://www.contoso-shop.test/"},
                         _priority="Low", _resourceType="image", _fromCache="memory"),
              resp_extra={"_transferSize": 0, "_error": None}),
        entry("GET", "https://ads.tracker.test/pixel.gif", 0, "", None, start_ms=505, http_version="",
              req_headers=[("Referer", "https://www.contoso-shop.test/")], resp_headers=[], status_text="",
              t=chrome_t(blocked=0.5, send=-1, wait=-1, receive=-1),
              extra=dict(base, serverIPAddress="", _initiator={"type": "parser"}, _priority="Low",
                         _resourceType="image"),
              resp_extra={"_transferSize": 0, "_error": "net::ERR_BLOCKED_BY_CLIENT"}, body_size=-1),
        entry("GET", "https://www.contoso-shop.test/old-page", 302, "", "", start_ms=700,
              resp_headers=[("Location", "/new-page"), ("content-length", "0")],
              extra=dict(base, _priority="VeryHigh", _resourceType="document"),
              resp_extra={"redirectURL": "/new-page", "_transferSize": 120, "_error": None}),
        entry("GET", "https://www.contoso-shop.test/missing.js", 404, "text/html", "<h1>Not Found</h1>", start_ms=720,
              extra=dict(base, _priority="Low", _resourceType="script"), resp_extra={"_transferSize": 210, "_error": None}),
        entry("POST", "https://www.contoso-shop.test/api/checkout", 500, "application/json",
              '{"error":"upstream timeout","traceId":"00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01"}',
              start_ms=900, req_headers=[("Content-Type", "application/json"), ("Origin", "https://www.contoso-shop.test")],
              post={"mimeType": "application/json", "text": '{"cartId":"c-1001","payment":"card"}'},
              resp_headers=[("Content-Type", "application/json"), ("x-ms-request-id", "e3b0c442-98fc-1c14-9afb-f4c8996fb924")],
              t=chrome_t(wait=2400.0, receive=3.0),
              extra=dict(base, _priority="High", _resourceType="xhr"), resp_extra={"_transferSize": 260, "_error": None}),
        entry("GET", "wss://ws.contoso-shop.test/live", 101, "", None, start_ms=1000,
              req_headers=[("Upgrade", "websocket"), ("Connection", "Upgrade"), ("Sec-WebSocket-Version", "13"),
                           ("Sec-WebSocket-Key", "dGhlIHNhbXBsZSBub25jZQ==")],
              resp_headers=[("Upgrade", "websocket"), ("Connection", "Upgrade"),
                            ("Sec-WebSocket-Accept", "s3pPLMBiTxaQ9kYGzzhZRbK+xOo=")],
              t=chrome_t(wait=35.0, receive=0.0),
              extra=dict(base, _priority="Low", _resourceType="websocket", _webSocketMessages=[
                  {"type": "send", "time": 1791363601.1, "opcode": 1, "data": '{"op":"subscribe","channel":"prices"}'},
                  {"type": "receive", "time": 1791363601.2, "opcode": 1, "data": '{"channel":"prices","sku":"A-1","price":9.99}'},
                  {"type": "receive", "time": 1791363602.4, "opcode": 2, "data": "AAECAw=="},
              ]),
              resp_extra={"_transferSize": 0, "_error": None}),
        entry("GET", "https://www.contoso-shop.test/new-page", 304, "text/html", None, start_ms=1100,
              resp_headers=[("etag", '"v42"')],
              extra=dict(base, _priority="VeryHigh", _resourceType="document", _fromCache="disk",
                         cache={"beforeRequest": {"lastAccess": "2026-10-07T08:59:00.000Z", "eTag": '"v42"', "hitCount": 3}}),
              resp_extra={"_transferSize": 0, "_error": None}),
    ]
    return log(entries, creator=("WebInspector", "537.36"), pages=[page])


def firefox():
    t = lambda **k: timings(**k)
    page = {"startedDateTime": "2026-10-07T10:00:00.000+01:00", "id": "page_1", "title": "Fabrikam Portal",
            "pageTimings": {"onContentLoad": 640, "onLoad": 1210}}
    entries = []
    e1 = entry("GET", "https://portal.fabrikam.test/", 200, "text/html; charset=utf-8", "<html><body>Portal</body></html>",
               start_ms=0, req_headers=[("Host", "portal.fabrikam.test"), ("User-Agent", "Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0"),
                                        ("Accept", "text/html"), ("Cookie", "fab_sid=s-77")],
               resp_headers=[("content-type", "text/html; charset=utf-8"), ("set-cookie", "fab_sid=s-77; Path=/; Secure")],
               t=t(blocked=0, dns=5, connect=40, ssl=22, send=0, wait=95, receive=4))
    e1["request"]["cookies"] = [{"name": "fab_sid", "value": "s-77"}]
    e1["response"]["cookies"] = [{"name": "fab_sid", "value": "s-77", "path": "/", "secure": True}]
    e1["request"]["headersSize"] = 412
    e1["request"]["bodySize"] = -1
    e1["response"]["bodySize"] = -1
    e1.update({"pageref": "page_1", "serverIPAddress": "198.51.100.20", "connection": "443", "_securityState": "secure"})
    entries.append(e1)
    e2 = entry("POST", "https://portal.fabrikam.test/api/search", 200, "application/json",
               '{"results":[{"id":1,"name":"alpha"},{"id":2,"name":"beta"}]}', start_ms=300,
               req_headers=[("Host", "portal.fabrikam.test"), ("Content-Type", "application/x-www-form-urlencoded"), ("Content-Length", "15")],
               post={"mimeType": "application/x-www-form-urlencoded", "text": "q=alpha&limit=2",
                     "params": [{"name": "q", "value": "alpha"}, {"name": "limit", "value": "2"}]},
               resp_headers=[("Content-Type", "application/json")], t=t(blocked=0, dns=0, connect=0, ssl=0, wait=55))
    e2.update({"pageref": "page_1", "serverIPAddress": "198.51.100.20", "connection": "443", "_securityState": "secure"})
    entries.append(e2)
    e3 = entry("GET", "http://insecure.fabrikam.test/banner.svg", 200, "image/svg+xml",
               '<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><rect width="10" height="10"/></svg>',
               start_ms=420, resp_headers=[("Content-Type", "image/svg+xml")])
    e3.update({"pageref": "page_1", "serverIPAddress": "198.51.100.21", "_securityState": "insecure"})
    entries.append(e3)
    return log(entries, creator=("Firefox", "131.0"), browser=("Firefox", "131.0"), pages=[page])


def safari():
    entries = []
    for i, (url, mime, fetch, status) in enumerate([
        ("https://news.example.test/", "text/html", "Network Load", 200),
        ("https://news.example.test/main.css", "text/css", "Memory Cache", 200),
        ("https://news.example.test/feed.json", "application/json", "Disk Cache", 200),
        ("https://news.example.test/gone", "text/plain", "Network Load", 404),
    ]):
        e = entry("GET", url, status, mime, "safari body %d" % i, start_ms=i * 50,
                  t=timings(blocked=-1, dns=-1, connect=-1, ssl=-1, send=0, wait=20 + i, receive=1))
        e["_fetchType"] = fetch
        e["_priority"] = "medium"
        e["pageref"] = "page_0"
        entries.append(e)
    pages = [{"startedDateTime": iso(0), "id": "page_0", "title": "news.example.test", "pageTimings": {"onContentLoad": 300, "onLoad": 450}}]
    return log(entries, creator=("WebKit Web Inspector", "1.0"), pages=pages)


def fiddler():
    entries = []
    t = {"blocked": 0, "dns": 3, "connect": 25, "ssl": 14, "send": 1, "wait": 78, "receive": 6}
    e1 = entry("GET", "https://api.northwind.test/orders/42", 200, "application/json", None, start_ms=0, t=t,
               req_headers=[("Host", "api.northwind.test"), ("Accept", "application/json"), ("Authorization", "Bearer synthetic-token-not-secret")],
               resp_headers=[("Content-Type", "application/json"), ("Content-Length", "34"), ("x-ms-request-id", "f1d2d2f9-24a1-4f1b-8a1a-111111111111")])
    body = '{"orderId":42,"status":"shipped"}\n'
    e1["response"]["content"] = {"size": len(body), "mimeType": "application/json",
                                 "text": base64.b64encode(body.encode()).decode(), "encoding": "base64"}
    e1["startedDateTime"] = "2026-10-07T10:15:02.1234567+01:00"
    e1["comment"] = "Fiddler session 12"
    e1["serverIPAddress"] = "192.0.2.44"
    e1["connection"] = "52314"
    entries.append(e1)
    e2 = entry("CONNECT", "https://api.northwind.test:443", 200, "", None, start_ms=0, t=t, status_text="Connection Established")
    e2["startedDateTime"] = "2026-10-07T10:15:02.0004000+01:00"
    entries.append(e2)
    e3 = entry("GET", "https://api.northwind.test/logo.gif", 200, "image/gif", base64.b64encode(GIF_1X1).decode(),
               encoding="base64", size=len(GIF_1X1), t=t)
    e3["startedDateTime"] = "2026-10-07T10:15:03.5000000+01:00"
    entries.append(e3)
    doc = log(entries, creator=("Fiddler", "5.0.20253.3311"))
    doc["log"]["creator"]["comment"] = "synthetic export"
    return doc


def har11():
    entries = []
    for i in range(3):
        t = {"blocked": 0, "dns": -1, "connect": -1, "send": 1, "wait": 10 + i, "receive": 2}
        e = entry("GET", "http://old.example.test/page%d" % i, 200, "text/plain", "page %d" % i, start_ms=i * 10, t=t)
        entries.append(e)
    return log(entries, version="1.1", creator=("LegacyExporter", "0.9"))


def base64_bodies():
    json_text = '{"encoded":"base64","ok":true}'
    entries = [
        entry("GET", "https://img.example.test/a.png", 200, "image/png", base64.b64encode(PNG_1X1).decode(),
              encoding="base64", size=len(PNG_1X1), start_ms=0),
        entry("GET", "https://img.example.test/b.gif", 200, "image/gif", base64.b64encode(GIF_1X1).decode(),
              encoding="base64", size=len(GIF_1X1), start_ms=10),
        entry("GET", "https://api.example.test/data", 200, "application/json", base64.b64encode(json_text.encode()).decode(),
              encoding="base64", size=len(json_text), start_ms=20),
        entry("GET", "https://files.example.test/blob.bin", 200, "application/octet-stream",
              base64.b64encode(bytes(range(256))).decode(), encoding="base64", size=256, start_ms=30),
        entry("POST", "https://upload.example.test/raw", 201, "text/plain", "created", start_ms=40,
              post={"mimeType": "application/octet-stream", "text": base64.b64encode(b"\x00\x01binary\xff").decode(), "encoding": "base64"}),
    ]
    return log(entries)


def compressed_bodies():
    text = '{"compressed":"%s","message":"This body was stored compressed in the HAR."}'
    gz_text = text % "gzip"
    df_text = text % "deflate"
    entries = [
        # Already decoded, as Chrome stores it: content.size is the decoded length.
        entry("GET", "https://z.example.test/decoded", 200, "application/json", text % "none", start_ms=0,
              resp_headers=[("Content-Encoding", "gzip"), ("Content-Type", "application/json")], body_size=60),
        entry("GET", "https://z.example.test/gzip", 200, "application/json", base64.b64encode(gzip.compress(gz_text.encode(), mtime=0)).decode(),
              encoding="base64", size=len(gz_text), start_ms=10,
              resp_headers=[("Content-Encoding", "gzip"), ("Content-Type", "application/json")]),
        entry("GET", "https://z.example.test/deflate", 200, "application/json", base64.b64encode(zlib.compress(df_text.encode())).decode(),
              encoding="base64", size=len(df_text), start_ms=20,
              resp_headers=[("Content-Encoding", "deflate"), ("Content-Type", "application/json")]),
        entry("GET", "https://z.example.test/brotli", 200, "application/json", BROTLI_B64, encoding="base64",
              size=len(BROTLI_TEXT), start_ms=30, resp_headers=[("Content-Encoding", "br"), ("Content-Type", "application/json")]),
        entry("GET", "https://z.example.test/zstd", 200, "application/json",
              base64.b64encode(b"\x28\xb5\x2f\xfd" + b"\x00" * 12).decode(), encoding="base64", size=99, start_ms=40,
              resp_headers=[("Content-Encoding", "zstd"), ("Content-Type", "application/json")]),
    ]
    return log(entries)


def minus_one():
    t = {"blocked": -1, "dns": -1, "connect": -1, "ssl": -1, "send": 0, "wait": 15, "receive": -1}
    entries = [
        entry("GET", "https://unknown.example.test/a", 200, "text/plain", "a", start_ms=0, t=t, headers_size=-1, body_size=-1),
        entry("GET", "https://unknown.example.test/b", 200, "text/plain", "bb", start_ms=5,
              t={"blocked": -1, "dns": 4, "connect": 30, "ssl": 20, "send": 1, "wait": 10, "receive": 2}, headers_size=-1, body_size=-1),
    ]
    entries[0]["time"] = 15
    entries[0]["response"]["content"]["size"] = -1
    return log(entries)


def failures():
    def fail(url, err, ms):
        e = entry("GET", url, 0, "", None, start_ms=ms, status_text="", http_version="",
                  t=timings(blocked=0.2, send=-1, wait=-1, receive=-1), body_size=-1)
        e["response"]["_error"] = err
        return e
    entries = [
        fail("https://blocked.example.test/ad.js", "net::ERR_BLOCKED_BY_CLIENT", 0),
        fail("https://nxdomain.example.test/", "net::ERR_NAME_NOT_RESOLVED", 10),
        fail("https://reset.example.test/api", "net::ERR_CONNECTION_RESET", 20),
        entry("GET", "https://ok.example.test/", 200, "text/plain", "fine", start_ms=30),
    ]
    entries[3]["response"]["status"] = 0  # status 0 without _error also counts as failed
    entries[3]["response"]["content"]["text"] = ""
    return log(entries)


def filter_fixture():
    """Entries designed for the SPEC 6.4 filter expressions. Entry N (1-based) starts N*100 ms in."""
    E = []

    def add(method, url, status, mime, *, req=(), resp=(), size=1000, time_ms=100.0, extra=None, resp_extra=None):
        n = len(E) + 1
        t = timings(blocked=0, dns=-1, connect=-1, send=0, wait=time_ms, receive=0)
        e = entry(method, url, status, mime, "x" * 10, start_ms=n * 100, req_headers=req, resp_headers=resp, t=t,
                  extra=extra, resp_extra=dict({"_transferSize": size}, **(resp_extra or {})))
        e["time"] = time_ms
        E.append(e)

    add("GET", "https://www.contoso.com/", 200, "text/html",
        resp=[("Content-Type", "text/html"), ("X-Cache", "TCP_MISS from a23-1-2-3"), ("x-azure-ref", "ref-1")],
        extra={"_resourceType": "document"})                                                  # 1
    add("GET", "https://api.contoso.com/v1/items?page=2", 200, "application/json",
        req=[("Authorization", "Bearer filter-fixture"), ("Accept", "application/json")], size=150_000, time_ms=2500,
        extra={"_resourceType": "fetch"})                                                     # 2
    add("POST", "https://api.contoso.com/v1/login", 403, "application/json",
        resp=[("x-ms-request-id", "req-3")], extra={"_resourceType": "xhr"})                   # 3
    add("GET", "https://cdn.fabrikam.net/logo.png", 200, "image/png", resp=[("X-Cache", "TCP_HIT")], size=50_000,
        extra={"_resourceType": "image", "_fromCache": "memory"})                             # 4
    add("GET", "http://legacy.contoso.com/old", 301, "text/html", resp=[("Location", "https://www.contoso.com/")],
        extra={"_resourceType": "document"})                                                  # 5
    add("GET", "https://www.contoso.com/app.js", 500, "application/javascript", time_ms=3000,
        extra={"_resourceType": "script"})                                                    # 6
    add("GET", "https://contoso.com/style.css", 503, "text/css", extra={"_resourceType": "stylesheet"})  # 7
    add("GET", "https://tracker.example.org/pixel.gif", 0, "", size=0,
        extra={"_resourceType": "image"}, resp_extra={"_error": "net::ERR_BLOCKED_BY_CLIENT"})  # 8
    add("PUT", "https://api.contoso.com/v1/items/7", 204, "", extra={"_resourceType": "fetch"})  # 9
    add("GET", "https://fonts.fabrikam.net/font.woff2", 200, "font/woff2", extra={"_resourceType": "font"})  # 10
    add("GET", "wss://ws.contoso.com/socket", 101, "", extra={"_resourceType": "websocket"})  # 11
    add("POST", "https://www.contoso.com/upload", 413, "image/png", size=200_000,
        req=[("Content-Type", "image/png")], extra={"_resourceType": "fetch"})               # 12
    # Store in reverse file order so that sorting by startedDateTime is exercised.
    return log(list(reversed(E)))


SECRETS = {
    "bearer": "plantedBearerToken0123456789abcdef",
    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwbGFudGVkLXVzZXItNDIiLCJuYW1lIjoiUGxhbnRlZCBVc2VyIiwiaWF0IjoxNzkxMzYzNjAwfQ.c2lnbmF0dXJlLXBsYW50ZWQtZm9yLXRlc3Rz",
    "basic_user": "planteduser",
    "basic_password": "plantedBasicPassw0rd",
    "cookie": "plantedSessionCookieValue7f3a9",
    "set_cookie": "plantedSetCookieValue55aa",
    "api_key": "plantedApiKey-9988776655",
    "proxy": "plantedProxyCredentialValue",
    "access_token_query": "plantedAccessTokenInQuery42",
    "id_token_redirect": "plantedIdTokenInRedirect77",
    "refresh_token_body": "plantedRefreshToken31337",
    "access_token_body": "plantedAccessTokenInBody99",
    "code_location": "plantedAuthCode1234",
    "client_secret": "plantedClientSecret5678",
    "password_form": "plantedFormPasswordXYZ",
    "sig": "plantedSignatureValueAbc",
    "saml": "plantedSamlResponseValue",
    "custom_header": "plantedCustomHeaderSecret",
    "account_regex": "ACCT-12345678",
    "bearer_in_body": "plantedBearerInBodyText",
    "referer_token": "plantedTokenInReferer",
    "initiator_token": "plantedTokenInInitiator",
    "page_title_token": "plantedTokenInPageTitle",
    "base64_body_token": "plantedTokenInBase64Body",
    "websocket_bearer": "plantedBearerInWebSocket",
    "graph_password_json": "plantedJsonPasswordValue",
}


def secrets_fixture():
    S = SECRETS
    basic = base64.b64encode(("%s:%s" % (S["basic_user"], S["basic_password"])).encode()).decode()
    proxy = base64.b64encode(("proxyuser:%s" % S["proxy"]).encode()).decode()
    pages = [{"startedDateTime": iso(0), "id": "page_1",
              "title": "https://app.contoso.test/callback?access_token=%s" % S["page_title_token"],
              "pageTimings": {"onContentLoad": 10, "onLoad": 20}}]
    e1 = entry("GET", "https://api.contoso.test/me?access_token=%s&view=full" % S["access_token_query"], 200, "application/json",
               '{"user":"planted","echo":"session=%s","note":"Authorization: Bearer %s"}' % (S["cookie"], S["bearer_in_body"]),
               start_ms=0,
               req_headers=[("Authorization", "Bearer " + S["bearer"]), ("Cookie", "session=%s; theme=dark" % S["cookie"]),
                            ("X-Api-Key", S["api_key"]), ("Proxy-Authorization", "Basic " + proxy),
                            ("X-Custom-Secret", S["custom_header"]),
                            ("Referer", "https://app.contoso.test/home?access_token=%s" % S["referer_token"])],
               resp_headers=[("Set-Cookie", "refresh=%s; Path=/; HttpOnly" % S["set_cookie"]), ("Content-Type", "application/json")])
    e1["request"]["cookies"] = [{"name": "session", "value": S["cookie"]}, {"name": "theme", "value": "dark"}]
    e1["response"]["cookies"] = [{"name": "refresh", "value": S["set_cookie"], "path": "/", "httpOnly": True}]
    e1["_initiator"] = {"type": "script", "url": "https://app.contoso.test/app.js?access_token=%s" % S["initiator_token"]}
    e1["pageref"] = "page_1"
    e2 = entry("POST", "https://login.contoso.test/oauth2/token", 200, "application/json",
               json.dumps({"access_token": S["access_token_body"], "refresh_token": S["refresh_token_body"],
                           "id_token": S["jwt"], "token_type": "Bearer", "expires_in": 3600}),
               start_ms=100, req_headers=[("Content-Type", "application/x-www-form-urlencoded"), ("Authorization", "Basic " + basic)],
               post={"mimeType": "application/x-www-form-urlencoded",
                     "text": "grant_type=authorization_code&code=%s&client_id=app&client_secret=%s" % (S["code_location"], S["client_secret"]),
                     "params": [{"name": "grant_type", "value": "authorization_code"}, {"name": "code", "value": S["code_location"]},
                                {"name": "client_id", "value": "app"}, {"name": "client_secret", "value": S["client_secret"]}]})
    e3 = entry("GET", "https://login.contoso.test/authorize?client_id=app", 302, "", "", start_ms=200,
               resp_headers=[("Location", "https://app.contoso.test/callback?code=%s&state=xyz" % S["code_location"])],
               resp_extra={"redirectURL": "https://app.contoso.test/callback#id_token=%s&state=xyz" % S["id_token_redirect"]})
    e4 = entry("POST", "https://app.contoso.test/login", 200, "text/html",
               "<p>Welcome</p><script>var t='%s';</script><p>Account ACCT-12345678</p>" % S["jwt"], start_ms=300,
               req_headers=[("Content-Type", "application/x-www-form-urlencoded")],
               post={"mimeType": "application/x-www-form-urlencoded",
                     "text": "username=planted&password=%s&SAMLResponse=%s" % (S["password_form"], S["saml"]),
                     "params": [{"name": "username", "value": "planted"}, {"name": "password", "value": S["password_form"]},
                                {"name": "SAMLResponse", "value": S["saml"]}]})
    e5 = entry("GET", "https://store.contoso.test/blob/file.txt?sv=2022-11-02&sig=%s&se=2026-10-08" % S["sig"], 200, "text/plain", "file",
               start_ms=400)
    b64json = base64.b64encode(json.dumps({"access_token": S["base64_body_token"], "ok": True}).encode()).decode()
    e6 = entry("GET", "https://api.contoso.test/token-b64", 200, "application/json", b64json, encoding="base64", size=60, start_ms=500)
    e7 = entry("GET", "wss://ws.contoso.test/live", 101, "", None, start_ms=600)
    e7["_webSocketMessages"] = [{"type": "send", "time": 1791363600.5, "opcode": 1,
                                 "data": '{"auth":"Bearer %s"}' % S["websocket_bearer"]}]
    e8 = entry("POST", "https://graph.contoso.test/v1/users", 201, "application/json", '{"id":"u-1"}', start_ms=700,
               req_headers=[("Content-Type", "application/json")],
               post={"mimeType": "application/json", "text": json.dumps({"user": "planted", "password": S["graph_password_json"]})})
    return log([e1, e2, e3, e4, e5, e6, e7, e8], pages=pages)


def saz_fixture(path):
    """A Fiddler Session Archive with an HTTPS JSON call (chunked + gzip), a form POST, a CONNECT, and a session without response."""
    import zipfile

    def meta(sid, begin, https=False, comment=None):
        flags = ['<SessionFlag N="x-hostip" V="192.0.2.%d" />' % (10 + sid), '<SessionFlag N="x-clientport" V="5%04d" />' % sid,
                 '<SessionFlag N="x-processinfo" V="msedge:4242" />']
        if https:
            flags.append('<SessionFlag N="x-https" V="true" />')
        if comment:
            flags.append('<SessionFlag N="ui-comments" V="%s" />' % comment)
        return ('<?xml version="1.0" encoding="utf-8"?>\n<Session SID="%d" BitFlags="0">'
                '<SessionTimers ClientConnected="2026-10-07T10:00:0%d.0000000+00:00" ClientBeginRequest="2026-10-07T10:00:0%d.1000000+00:00" '
                'FiddlerBeginRequest="2026-10-07T10:00:0%d.1100000+00:00" ServerConnected="2026-10-07T10:00:0%d.1200000+00:00" '
                'ServerGotRequest="2026-10-07T10:00:0%d.1300000+00:00" ServerBeginResponse="2026-10-07T10:00:0%d.2300000+00:00" '
                'ServerDoneResponse="2026-10-07T10:00:0%d.2500000+00:00" DNSTime="4" TCPConnectTime="20" HTTPSHandshakeTime="%d" />'
                '<SessionFlags>%s</SessionFlags></Session>') % (sid, begin, begin, begin, begin, begin, begin, begin, 15 if https else 0, "".join(flags))

    body = b'{"saz":"chunked gzip json","ok":true}'
    gz = gzip.compress(body, mtime=0)
    chunked = b"%x\r\n" % 10 + gz[:10] + b"\r\n" + b"%x\r\n" % (len(gz) - 10) + gz[10:] + b"\r\n0\r\n\r\n"
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", '<?xml version="1.0" encoding="utf-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="txt" ContentType="text/plain" /></Types>')
        z.writestr("_index.htm", "<html><body>synthetic</body></html>")
        z.writestr("raw/1_c.txt", b"CONNECT api.northwind.test:443 HTTP/1.1\r\nHost: api.northwind.test:443\r\n\r\n")
        z.writestr("raw/1_s.txt", b"HTTP/1.1 200 Connection Established\r\nFiddlerGateway: Direct\r\n\r\n")
        z.writestr("raw/1_m.xml", meta(1, 1, https=True))
        z.writestr("raw/2_c.txt", b"GET https://api.northwind.test/v1/orders?id=42 HTTP/1.1\r\nHost: api.northwind.test\r\nAccept: application/json\r\nCookie: nw=1\r\n\r\n")
        z.writestr("raw/2_s.txt", b"HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Encoding: gzip\r\nTransfer-Encoding: chunked\r\n\r\n" + chunked)
        z.writestr("raw/2_m.xml", meta(2, 2, https=True, comment="slow order lookup"))
        z.writestr("raw/3_c.txt", b"POST http://legacy.northwind.test/login HTTP/1.1\r\nHost: legacy.northwind.test\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: 19\r\n\r\nuser=a&remember=yes")
        z.writestr("raw/3_s.txt", b"HTTP/1.1 302 Found\r\nLocation: /home\r\nSet-Cookie: sid=abc; Path=/; HttpOnly\r\nContent-Length: 0\r\n\r\n")
        z.writestr("raw/3_m.xml", meta(3, 3))
        z.writestr("raw/4_c.txt", b"GET http://down.northwind.test/ HTTP/1.1\r\nHost: down.northwind.test\r\n\r\n")
        z.writestr("raw/4_m.xml", meta(4, 4))


def main():
    os.makedirs(OUT, exist_ok=True)
    chromium_bytes = write("chromium.har", chromium())
    with open(os.path.join(OUT, "chromium.har.gz"), "wb") as f:
        f.write(gzip.compress(chromium_bytes, mtime=0))
    write("firefox.har", firefox())
    write("safari.har", safari())
    write("fiddler.har", fiddler())
    write("har11.har", har11())
    write("base64-bodies.har", base64_bodies())
    write("compressed-bodies.har", compressed_bodies())
    write("minus-one.har", minus_one())
    write("failures.har", failures())
    write("filter.har", filter_fixture())
    write("secrets.har", secrets_fixture())
    with open(os.path.join(OUT, "secrets.planted.txt"), "w", encoding="utf-8") as f:
        for v in SECRETS.values():
            f.write(v + "\n")
        # Derived forms that must also disappear.
        f.write(base64.b64encode(("%s:%s" % (SECRETS["basic_user"], SECRETS["basic_password"])).encode()).decode() + "\n")
        f.write(base64.b64encode(("proxyuser:%s" % SECRETS["proxy"]).encode()).decode() + "\n")
        f.write(SECRETS["jwt"].split(".")[2] + "\n")
    write("bom.har", har11(), bom=True)
    nover = har11()
    del nover["log"]["version"]
    write("no-version.har", nover)
    write("not-har.json", {"name": "not a har", "items": [1, 2, 3], "nested": {"log": "this is a string"}})
    write("log-without-entries.json", {"log": {"version": "1.2", "creator": {"name": "x", "version": "1"}}})

    # Truncated: cut in the middle of the fourth entry.
    full = chromium_bytes.decode("utf-8")
    marker = '"url": "https://cdn.contoso-shop.test/img/pixel.png"'
    cut = full.index(marker) + 20
    truncated = full[:cut].encode("utf-8")
    with open(os.path.join(OUT, "truncated.har"), "wb") as f:
        f.write(truncated)
    # Malformed: an invalid number inside entry 2's response.
    doc = json.dumps(chromium(), indent=2)
    target = '"status": 200'
    first = doc.index(target)
    second = doc.index(target, first + 1)
    third = doc.index(target, second + 1)
    bad = doc[:third] + '"status": 20x0' + doc[third + len(target):]
    with open(os.path.join(OUT, "malformed.har"), "w", encoding="utf-8") as f:
        f.write(bad)
    bad_offset = len(bad[:third + len('"status": ')].encode("utf-8"))
    line = bad[:third].count("\n") + 1
    column = bad_offset - (len(bad[:bad.rfind("\n", 0, third) + 1].encode("utf-8"))) + 1
    with open(os.path.join(OUT, "malformed.expected.json"), "w") as f:
        json.dump({"recovered": 2, "offset": bad_offset, "line": line, "column": column,
                   "path": "$.log.entries[2].response.status"}, f, indent=2)
    with open(os.path.join(OUT, "truncated.expected.json"), "w") as f:
        json.dump({"recovered": 4, "length": len(truncated)}, f, indent=2)
    saz_dir = os.path.join("tests", "fixtures", "saz")
    os.makedirs(saz_dir, exist_ok=True)
    saz_fixture(os.path.join(saz_dir, "sample.saz"))
    print("fixtures written to", OUT, "and", saz_dir)


if __name__ == "__main__":
    main()
