using System.Globalization;
using System.Net;
using HarLens.Core.Http;

namespace HarLens.Net;

/// <summary>Turns a hop into an HttpRequestMessage, keeping the composed headers as close to verbatim as .NET allows.</summary>
internal static class RequestMessageFactory
{
    public const string AutoAcceptEncoding = "gzip, deflate, br";

    // Headers .NET only accepts on HttpContent.
    private static readonly HashSet<string> s_contentHeaders = new(StringComparer.OrdinalIgnoreCase)
    {
        "Content-Type", "Content-Encoding", "Content-Language", "Content-Disposition", "Content-Location",
        "Content-MD5", "Content-Range", "Expires", "Last-Modified", "Allow",
    };

    public static HttpRequestMessage Create(HopRequest hop, RequestOptions options, List<string> notices, out byte[]? sentBody)
    {
        var message = new HttpRequestMessage(new HttpMethod(hop.Method), hop.Uri);
        switch (hop.Version)
        {
            case HttpVersionPreference.Http11:
                message.Version = HttpVersion.Version11;
                message.VersionPolicy = HttpVersionPolicy.RequestVersionExact;
                break;
            case HttpVersionPreference.Http2:
                // curl --http2 falls back to HTTP/1.1 when the server does not offer h2.
                message.Version = HttpVersion.Version20;
                message.VersionPolicy = HttpVersionPolicy.RequestVersionOrLower;
                break;
            default:
                // HTTP/1.1, upgraded to HTTP/2 when ALPN offers it on https.
                message.Version = HttpVersion.Version11;
                message.VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher;
                break;
        }

        byte[]? bodyBytes = hop.Body?.Bytes;
        HttpContent? content = bodyBytes is null ? null : new ByteArrayContent(bodyBytes);
        bool hostSet = false;
        bool contentTypeSet = false;
        bool acceptEncodingSet = false;

        foreach (var header in hop.Headers)
        {
            string name = header.Name;
            string value = header.Value;

            // Pseudo-headers are generated by the HTTP/2 layer from the URL and method.
            if (name.StartsWith(':'))
            {
                continue;
            }

            if (hop.StripCredentials && RedirectPolicy.IsCredentialHeader(name))
            {
                continue;
            }

            if (name.Equals("Content-Length", StringComparison.OrdinalIgnoreCase))
            {
                // Computed from the body (SPEC 7.1). Mention it only when the edited value would have been wrong.
                string actual = (bodyBytes?.Length ?? 0).ToString(CultureInfo.InvariantCulture);
                if (value.Trim() != actual)
                {
                    notices.Add($"Content-Length is computed from the body; the composed value '{value}' was not sent");
                }

                continue;
            }

            if (value.Contains('\r') || value.Contains('\n') || value.Contains('\0'))
            {
                notices.Add($"Header '{name}' was not sent: values cannot contain line breaks or NUL characters");
                continue;
            }

            if (name.Equals("Host", StringComparison.OrdinalIgnoreCase))
            {
                if (hostSet)
                {
                    notices.Add($"Only the first Host header is sent; 'Host: {value}' was dropped");
                    continue;
                }

                try
                {
                    message.Headers.Host = value.Trim();
                    hostSet = true;
                }
                catch (FormatException)
                {
                    notices.Add($"Host header '{value}' is not a valid host[:port] and was not sent");
                }

                continue;
            }

            if (s_contentHeaders.Contains(name))
            {
                if (content is null)
                {
                    content = new ByteArrayContent([]);
                    bodyBytes = [];
                    notices.Add($"The {name} header was sent with an empty body");
                }

                if (name.Equals("Content-Type", StringComparison.OrdinalIgnoreCase))
                {
                    if (contentTypeSet)
                    {
                        notices.Add($"Only the first Content-Type header is sent; '{value}' was dropped");
                        continue;
                    }

                    contentTypeSet = true;
                    if (hop.Body is { ReplacesUserContentType: true, ContentType: { } replacement })
                    {
                        value = replacement;
                    }
                }

                if (!content.Headers.TryAddWithoutValidation(name, value))
                {
                    notices.Add($"Header '{name}' could not be sent");
                }

                continue;
            }

            if (name.Equals("Accept-Encoding", StringComparison.OrdinalIgnoreCase))
            {
                acceptEncodingSet = true;
            }

            if (!message.Headers.TryAddWithoutValidation(name, value))
            {
                notices.Add($"Header '{name}' could not be sent: not a valid header name");
            }
        }

        if (!contentTypeSet && content is not null && hop.Body?.ContentType is { } defaultType)
        {
            content.Headers.TryAddWithoutValidation("Content-Type", defaultType);
        }

        // curl --compressed behaviour.
        if (options.AutoDecompress && !acceptEncodingSet)
        {
            message.Headers.TryAddWithoutValidation("Accept-Encoding", AutoAcceptEncoding);
        }

        message.Content = content;
        sentBody = bodyBytes;
        return message;
    }
}
